### ISSUE TITLE
clarity and importance of mitigations against spam, harassment and abuse

### ISSUE THREAD

**Issue by npdoty** [coopdanger/ietf-wg-mimi#17]
Hooks to enable mitigations by services and users for spam, harassment and other kinds of abuse are prerequisite to any successful interoperable work here. However, the charter explicitly mentions spam, abuse and moderation only in suggesting that it would require rechartering ("metadata processing to manage spam and abuse" "moderation across systems") or that it's out of scope (development of anti-spam algorithms, which, fine). I'm not sure what "metadata processing" means in this context, but I don't want the group to have to immediately recharter to address one of the largest challenging problems for interoperable federated messaging. Interoperable sending of abuse reports, message franking, blocking and blocklists, etc. seem essential to me and I don't know if they're in scope.

The BoF discussion seemed to make it clear that most expected that spam and abuse would at least be considered, but I don't think the charter needs to introduce more confusion or limits on being able to work on it. These aren't features to postpone.

**Comment by rohan-wire** [comment]
Hi Nick,
I don't think anyone expects that two systems which implement specs and recommendations produced by MIMI will be deployed without SPAM or abuse prevention. I think the current charter text is sufficient to allow that. Below is my take on what is allowed by the charter:

- The introduction problem is in scope, so explicit authorization to communicate (and lack of or removal of that authorization) will be included in MIMI and conveyed between the system of the target and the system of the initiator.
- What is explicitly out of scope is developing anti-spam algorithms (for which IETF doesn't have the expertise anyway).
- What requires a recharter is spam metadata. For example reputation protocols that share information about spam or suspected spam among several systems which may not have been a party to any of the spam communications; or a protocol which allows a receiver to make granular rankings of the "spaminess" of a particular message. Note that both of these can be implemented in another layer (even in an interoperable way) without developing them in the MIMI WG.

I hope this helps.
Thanks,
-rohan

**Comment by npdoty** [comment]
"metadata" will mean to many readers way more than just the development of spam scoring systems (which I would be fine leaving out of scope). For example, where did this message come from, what server is the host for the initiator, what is the endpoint for reporting an abusive message, how many messages came from this endpoint in the last hour, is this the same user as another user on another service that the user has blocked, etc.

I would prefer if charters used explicit common language rather than relying on the implicit assumptions of the authors.

**Comment by turt2live** [comment]
The servers and clients speaking the protocols MIMI produces would also be able to do their own processing of messages to determine if something looks like spam or abuse, and prevent it from reaching their users (or at least the charter permits such thinking). In this sense, the working group is aiming to describe *how* to send messages between services rather than solve messaging as a whole.

**Comment by npdoty** [comment]
If metadata is out of scope, then I expect it would be extremely difficult for servers to limit abuse in end-to-end encrypted messaging.

Reporting abuse across servers (which might be part of "moderation across servers") is likely to be especially important in interoperable federated settings (as we have seen in the Matrix case). Without providing for that capability, a dominant provider can interoperate, show that spam comes from interoperable servers without any way of reporting or stopping it, and undermine the case for interoperability.

**Comment by turt2live** [comment]
I'm not sure that's a reason to bring abuse mitigations into the charter though? The protocol certainly needs to consider an amount of metadata as well as anti-abuse, but the working group doesn't need to get stuck in the weeds at this stage for how to solve [decentralized] reputation or other anti-abuse measures. The charter forbids the working group from getting stuck in the weeds, but does not prevent consideration of features for a later phase of discussion.

**Comment by bifurcation** [comment]
I think I'm largely on the same page as @rohan-wire here.  The line I would draw is between "data that anti-abuse processes can operate on" and "how the anti-abuse process operates".  The former being in-scope and the latter out of scope.  Basically, if a server federates with MIMI, then the protocols should provide enough data for the server to apply some reasonable set of anti-abuse policies.

Looking at the list of examples that @npdoty provided above through this lens:

* Where did this message come from - Clearly in-scope.
* What server is the host for the initiator - Clearly in-scope.
* What is the endpoint for reporting an abusive message - Probably out-of-scope, though something like an error code for "I am refusing to deliver this because I think it's abusive" could be in-scope.
* How many messages came from this endpoint in the last hour - Definitely out.
* Is this the same user as another user on another service that the user has blocked, etc. - Definitely out.

The latter two even have a "centralized monitoring" smell to them!  It seems like the right sequence of events here is: (1) Define base MIMI with basic metadata on which servers can make basically acceptable anti-abuse decisions, (2) let people experiment with more advanced techniques (e.g., aggregating data across servers), and (3) if some of those techniques turn out to be useful, bring them into MIMI later.

In terms of charter language, it might be good to clarify that (a) the protocol needs to provide a certain baseline level of metadata, and (b) "Metadata processing to manage spam and abuse" isn't meant to rule that out.  But generally the intent of the current text seems correct.

**Comment by ekr** [comment]
I agree with @bifurcation here. If someone wants to propose a change to the PR that tries to address that metadata baseline question, that seems valuable, but it also has to be balanced against whatever goals we have for anonymity and at least making room for some level of deniability (though of course MLS doesn't offer the latter at present).

**Comment by npdoty** [comment]
#27 is my minimal attempt to clarify the idea that baseline data to enable anti-spam and anti-abuse is in scope while clarifying that algorithms to process the data is out of scope.

**Comment by npdoty** [comment]
I'm still concerned that interoperable moderation is considered out of scope. Excluding that interoperability seems to benefit those players who want to discourage messaging interoperability by making interoperable messaging more likely to lead to inundations of abusive behavior. As suggested, we can instead encourage vendors to do this in non-interoperable ways for now and suggest re-chartering later.
